# Generated by Django 5.1.4 on 2024-12-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_notification_rename_category_expense_name_customuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='expenselimit',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='name',
            new_name='category',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='ExpenseLimit',
        ),
    ]
